apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/alexeyauslender/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination: 
    server: https://kubernetes.default.svc
    namespace: test-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true